### ISSUE TITLE
Manifest Validation Checks

### ISSUE THREAD

**Issue by Zidane** [SpongePowered/plugin-spi#10]
I read over my code and realized that no validation exists for the Manifest we discover and provide as part of a PluginFile in one of the discover strategies. A possible fail case is a project bootstrapping Mixin, passing the manifests to Mixin, and if the mixin configuration file specified (`MixinConfigs: test.json`) doesn't exist Mixin treats it as a hard stop.

Now one could state "This isn't our problem" and I would almost say "you are correct" but I want something on the record before the inevitable ticket comes asking why we don't "check it" or simply why we don't pass a validator back from the JVM language service.

Thoughts?

**Comment by jamierocks** [comment]
Yeah, I say let the language service do a dance with the manifest - have the capability to verify if the service deems it neccasery.
