### ISSUE TITLE
Compatibility with legacy plugins (Game <= 1.12.2, Sponge API <= 8)

### ISSUE THREAD

**Issue by CatMe0w** [SpongePowered/plugin-spi#19]
Legacy plugins have a `mcmod.info` instead of a `plugin.json`, causing them not loading in Sponge 1.16 versions.
Will you consider drop API 7 plugins support in latest Sponge version?

**Comment by ItsDoot** [comment]
Gonna need an explanation here. `plugin-spi` is neither version dependent nor platform dependent; just a generic framework we use for API 8+.

If you mean support for API 7 Sponge plugins, we have no plans whatsoever to support them on API 8.
If you mean for versions older than what API 8 is currently targetting, we also have no plans for that.

**Comment by zml2008** [comment]
please explain?

**Comment by CatMe0w** [comment]
Sorry for the incomplete title.

Thank you for such fast replies.
